name: OpenWrt Publish Release


description: Merge firmware artifacts and create release



inputs:


  release-tag-prefix:

    required: true

    description: Release tag prefix


  release-files:

    required: false

    description: Release files



runs:


  using: composite


  steps:



    - name: Prepare release directory

      shell: bash

      run: |

        set -eux


        rm -rf downloaded

        mkdir -p downloaded


        mkdir -p public


        mkdir -p public/firmware


        mkdir -p public/packages






    - name: Download workflow artifacts

      uses: actions/download-artifact@v4

      with:


        path: downloaded






    - name: Check downloaded artifacts

      shell: bash

      run: |

        set +e


        echo "=============================="

        echo "Downloaded artifacts"

        echo "=============================="


        if [ -d downloaded ]; then

          find downloaded -type f

        else

          echo "No downloaded directory"

        fi






    - name: Collect firmware

      shell: bash

      run: |

        set -eux


        if [ -d downloaded ]; then


          echo "Collect firmware"


          find downloaded -type f \( -name "*.bin" -o -name "*.img" -o -name "*.manifest" -o -name "*sha256sums" -o -name "*.buildinfo" \) -exec cp --parents {} public/firmware/ \;


        else


          echo "No artifacts"


        fi






    - name: Collect APK packages

      shell: bash

      run: |

        set -eux


        echo "===== APK packages ====="


        if [ -d downloaded ]; then


          find downloaded -type f -name "*.apk" -exec cp --parents {} public/packages/ \;


        else


          echo "No apk source"


        fi






    - name: Collect packages adb

      shell: bash

      run: |

        set -eux


        echo "===== packages.adb ====="


        if [ -d downloaded ]; then


          find downloaded -type f -name "packages.adb" -exec cp --parents {} public/packages/ \;


        else


          echo "No adb files"


        fi






    - name: Show release files

      shell: bash

      run: |

        set +e


        echo "=============================="

        echo "Release content"

        echo "=============================="


        find public -type f






    - name: Create Release

      uses: softprops/action-gh-release@v2


      with:


        tag_name: ${{ inputs.release-tag-prefix }}-${{ github.run_number }}


        name: "${{ inputs.release-tag-prefix }} Build ${{ github.run_number }}"


        files: |

          public/**


      env:


        GITHUB_TOKEN: ${{ github.token }}
