#!/bin/sh


if [ -f /etc/apk/third-party-packages ]; then


    while read pkg
    do

        apk add --allow-untrusted "$pkg"

    done < /etc/apk/third-party-packages


    rm -f /etc/apk/third-party-packages


fi


exit 0
