#!/bin/sh

PACKAGE_LIST="/etc/third-party-packages"

if [ ! -f "${PACKAGE_LIST}" ]; then

    exit 0

fi


apk update

while read pkg

do

    [ -z "$pkg" ] && continue

    echo "Installing third-party package:"
    echo "$pkg"

    apk add "$pkg"

done < "${PACKAGE_LIST}"

exit 0
