#!/bin/sh

echo "=========================================="
echo "Install third-party APK packages"
echo "=========================================="


APK_DIR="/usr/share/third-party"


if [ ! -d "$APK_DIR" ]; then

    echo "Missing third-party APK directory"

    exit 1

fi


for apk in "$APK_DIR"/*.apk
do

    [ -f "$apk" ] || continue


    echo "Installing:"
    echo "$apk"


    apk add \
        --allow-untrusted \
        "$apk"


done


echo "Third-party APK installation completed"


exit 0
