#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance

    procd_set_param command \
        /bin/sh \
        /etc/third-party/install_third_party_apk.sh

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}
