#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    [ -f /etc/third-party-apk-installed ] && return 0

    procd_open_instance
    procd_set_param command /usr/bin/install_third_party_apk.sh
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
