name: Build filogic


on:


  workflow_dispatch:


    inputs:


      docker:


        description: Enable docker packages


        required: false


        default: false


        type: boolean





  schedule:


    - cron: "0 2 1 * *"





concurrency:


  group: filogic-build


  cancel-in-progress: true





permissions:


  contents: read





jobs:





  build:





    strategy:


      fail-fast: false





      matrix:


        include:





          - device: GL-MT5000


            repo_url: https://github.com/m0eak/fanchmwrt.git


            repo_branch: mt5000


            config_file: config/mt5000.config


            sonic_fullcone: "true"





          - device: Tenda-BE12PRO


            repo_url: https://github.com/chasey-dev/immortalwrt-mt798x-rebase.git


            repo_branch: 25.12-dev-wifi7


            config_file: config/be12pro.config


            sonic_fullcone: "false"





    uses: ./.github/workflows/_openwrt-build-device.yml





    with:





      device: ${{ matrix.device }}





      repo_url: ${{ matrix.repo_url }}





      repo_branch: ${{ matrix.repo_branch }}





      config_file: ${{ matrix.config_file }}





      install_automake_117: "true"





      sonic_fullcone: ${{ matrix.sonic_fullcone }}





      docker: ${{ inputs.docker }}
