name: Build immortalwrt


on:

  workflow_dispatch:

    inputs:

      source:

       description: OpenWrt source

       required: false

       default: immortalwrt

       type: choice

       options:

         - openwrt
         - immortalwrt
      
      version:

        description: ImmortalWrt version/tag

        required: false

        default: ""

        type: string
        
      
      third_party:

        description: Enable third-party packages

        required: false

        default: false

        type: boolean
        

      docker:

        description: Enable docker packages

        required: false

        default: false

        type: boolean


      release:

        description: Create GitHub release

        required: false

        default: false

        type: boolean


  schedule:

    - cron: "0 2 2 1,7 *"


concurrency:

  group: immortalwrt-build

  cancel-in-progress: true


permissions:

  contents: write


jobs:


  build:


    strategy:

      fail-fast: false


      matrix:

        include:


          - device: immortalwrt

            config_file: config/immortalwrt.config


    uses: ./.github/workflows/_openwrt-build-device.yml


    with:

      device: ${{ matrix.device }}

      repo_url: ${{ inputs.source == 'immortalwrt' && 'https://github.com/immortalwrt/immortalwrt.git' || 'https://github.com/openwrt/openwrt.git' }}

      repo_branch: ${{ inputs.version != '' && inputs.version || (inputs.source == 'immortalwrt' && 'v25.12.1' || 'v25.12.5') }}

      config_file: ${{ matrix.config_file }}

      sonic_fullcone: "false"

      docker: ${{ inputs.docker }}

      release: ${{ inputs.release }}
