name: Build filogic

on:
  workflow_dispatch:
    inputs:
      docker:
        description: Enable docker packages
        required: false
        default: false
        type: boolean

      release:
        description: Create GitHub release
        required: false
        default: false
        type: boolean

  schedule:
    - cron: "0 2 1 1,4,7,10 *"


concurrency:
  group: filogic-build
  cancel-in-progress: true


permissions:
  contents: write


jobs:

  build_mt5000:

    name: Build GL-MT5000

    uses: ./.github/workflows/_openwrt-build-device.yml

    with:

      device: GL-MT5000

      repo_url: https://github.com/m0eak/fanchmwrt.git

      repo_branch: mt5000

      config_file: config/mt5000.config

      sonic_fullcone: "true"

      docker: ${{ inputs.docker }}

      release: ${{ inputs.release }}


  build_be12pro:

    name: Build Tenda-BE12PRO

    uses: ./.github/workflows/_openwrt-build-device.yml

    with:

      device: Tenda-BE12PRO

      repo_url: https://github.com/chasey-dev/immortalwrt-mt798x-rebase.git

      repo_branch: 25.12-dev-wifi7

      config_file: config/be12pro.config

      sonic_fullcone: "false"

      docker: ${{ inputs.docker }}

      release: ${{ inputs.release }}
