name: Build filogic


permissions:

  contents: write



on:


  schedule:


    - cron: "0 2 */4 * *"



  workflow_dispatch:


    inputs:


      docker:


        description: "是否编译 docker"


        required: false


        default: false


        type: boolean






jobs:



  GL-MT5000:



    name: Build GL-MT5000



    uses: ./.github/workflows/_openwrt-build-device.yml



    with:



      device: GL-MT5000



      repo_url: https://github.com/m0eak/fanchmwrt.git



      repo_branch: mt5000



      config_file: config/mt5000.config



      workflow_name: GL-MT5000



      install_automake_117: "true"



      sonic_fullcone: "true"



      docker: ${{ github.event.inputs.docker || 'false' }}



      release: "true"







  Tenda-BE12PRO:



    name: Build Tenda-BE12PRO



    uses: ./.github/workflows/_openwrt-build-device.yml



    with:



      device: Tenda-BE12PRO



      repo_url: https://github.com/chasey-dev/immortalwrt-mt798x-rebase.git



      repo_branch: 25.12-dev-wifi7



      config_file: config/be12pro.config



      workflow_name: Tenda-BE12PRO



      install_automake_117: "true"



      sonic_fullcone: "false"



      docker: ${{ github.event.inputs.docker || 'false' }}



      release: "true"
