name: Build GL-MT3600BE

on:

  workflow_dispatch:

    inputs:

      docker:

        description: Enable docker packages

        required: false

        default: false

        type: boolean

      release:

        description: Create GitHub release

        required: false

        default: false

        type: boolean


  schedule:

    - cron: "0 2 1 1,7 *"


concurrency:

  group: GL-MT3600BE-build

  cancel-in-progress: true


permissions:

  contents: write


jobs:

  build:

    uses: ./.github/workflows/_openwrt-build-device.yml


    with:

      device: GL-MT3600BE

      repo_url: https://github.com/immortalwrt/immortalwrt.git

      repo_branch: mt3600be

      config_file: config/mt3600be.config

      sonic_fullcone: "true"

      docker: ${{ inputs.docker }}

      release: ${{ inputs.release }}
