name: Build Cudy-TR3000-v1

on:

  workflow_dispatch:

    inputs:

      version:

        description: Cudy-TR3000-v1 version/tag

        required: false

        default: v25.12.5

        type: string
      
      docker:

        description: Enable docker packages

        required: false

        default: false

        type: boolean


      release:

        description: Create GitHub release

        required: false

        default: false

        type: boolean


  schedule:

    - cron: "0 2 7 1,7 *"


concurrency:

  group: Cudy-TR3000-v1-build

  cancel-in-progress: true


permissions:

  contents: write


jobs:


  build:


    strategy:

      fail-fast: false


      matrix:

        include:


          - device: Cudy-TR3000-v1

            repo_url: https://github.com/openwrt/openwrt.git

            repo_branch: ${{ github.event.inputs.tag || 'v25.12.5' }}

            config_file: config/tr3000.config


    uses: ./.github/workflows/_openwrt-build-device.yml


    with:

      device: ${{ matrix.device }}

      repo_url: ${{ matrix.repo_url }}

      repo_branch: ${{ matrix.repo_branch }}

      config_file: ${{ matrix.config_file }}

      sonic_fullcone: "true"

      docker: ${{ inputs.docker }}

      release: ${{ inputs.release }}
