name: Build Cudy-TR3000-v1-256MB

on:

  workflow_dispatch:

    inputs:

      source:

       description: OpenWrt source

       required: false

       default: openwrt

       type: choice

       options:

         - openwrt
         - immortalwrt

      version:

        description: Cudy TR3000 v1 (256MB) version/tag

        required: false

        default: ""

        type: string
      
      docker:

        description: Enable docker packages

        required: false

        default: false

        type: boolean


      release:

        description: Create GitHub release

        required: false

        default: false

        type: boolean


  schedule:

    - cron: "0 2 7 1,7 *"


concurrency:

  group: Cudy

  cancel-in-progress: true


permissions:

  contents: write


jobs:


  build:


    strategy:

      fail-fast: false


      matrix:

        include:


          - device: Cudy-TR3000-256MB

            config_file: config/tr3000.config


    uses: ./.github/workflows/_openwrt-build-device.yml


    with:

      device: ${{ matrix.device }}

      repo_url: ${{ inputs.source == 'immortalwrt' && 'https://github.com/immortalwrt/immortalwrt.git' || 'https://github.com/openwrt/openwrt.git' }}

      repo_branch: ${{ inputs.version != '' && inputs.version || (inputs.source == 'immortalwrt' && 'v25.12.1' || 'v25.12.5') }}

      config_file: ${{ matrix.config_file }}

      sonic_fullcone: "true"

      docker: ${{ inputs.docker }}

      release: ${{ inputs.release }}
