#!/bin/sh

FEED_FILE="/etc/apk/repositories.d/distfeeds.list"
MIRROR="https://mirror.nju.edu.cn/openwrt/releases"

if [ -f "${FEED_FILE}" ]; then

    sed -i -E \
        "s#https?://[^/]+/openwrt/releases#${MIRROR}#g" \
        "${FEED_FILE}"

fi

exit 0
